# Site settings
title: Side Character
description: > # this means to ignore newlines until "baseurl:"
  A website written by Joseph Moghadam (that's me)!
  Do I really have the gall to dedicate something to myself?
  Sometimes people accuse me of not saying a lot about myself.
  Now people who are curious about me may read something.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jmoghadam.github.io" # the base hostname & protocol for your site
github_username: jmoghadam

# Build settings
markdown: kramdown
