title: "Side Character"
description: > # this means to ignore newlines until "baseurl:"
  A website written by Joseph Moghadam (that's me)!
  Do I really have the gall to dedicate something to myself...?
  I'm not one of the main characters.
baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://jmoghadam.github.io" # the base hostname & protocol for your site
github_username: "jmoghadam"

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

gems:
  - jemoji
exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
